### PR TITLE
Move documentation to new site

### PR DESCRIPTION
**Pull request by c-knowles**
Update readme to reflect new documentation.

@mumoshu I'd like to merge this after collaborators are added to the new docs.

### CODE REVIEW

**Comment by mumoshu** [comment]
@c-knowles Thank you very much for your efforts in this area!

What I'm still unsure though is where we should host source code of the doc site.

IMHO, we should ideally host both kube-aws and its documentation in this single git repository, so that we can update both kube-aws and relevant docs altogether in a single PR.

So, for example, how about transferring contents of https://github.com/kube-aws/docs to the docs directory of this repo?
I've prepared https://github.com/mumoshu/kube-aws/tree/master/docs and https://mumoshu.gitbooks.io/test/# to show how it works. The former is the modified version of this git repository with the new docs included under the `docs/` directory, whereas the latter is the gitbook linked to my repo. Theoretically, we can do the same thing for this repo, too.

One thing we have to manage though is that we have to ask kubernetes-incubator admins to approve gitbook integration. Otherwise we can't link this repository with gitbook in the first place.

WDYT?

**Comment by mumoshu** [comment]
Btw, your choice of gitbook for hosting the kube-aws docs seems very reasonable. I just realized that by preparing the example mentioned above myself. Thank you very much for your efforts 👍

**Comment by mumoshu** [comment]
Hi @calebamiles!
Sorry for bothering you but we'd like to host our docs at https://www.gitbook.com.
In order to accomplish that, it seems like we have to ask you to approve gitbook integration for the kubernetes-incubator organization, as you seem to be an owner of the organization who has the privilege to do so.

I've already requested an approval for the gitbook integration from GitHub:

image

Would you mind approving it?

Once you've approved it, I guess you can confirm the approval to be active by browsing https://github.com/apps/gitbook/installations/new and seeing if there is `kubernetes-incubator` in the list.

**Comment by mumoshu** [comment]
@c-knowles Btw, I had to move `book.json` to the root of the project https://github.com/mumoshu/kube-aws/blob/master/book.json and update book.json to include `"root: "docs"` to instruct gitbook to process only files under `docs/`.

**Comment by mumoshu** [comment]
// Linking this issue to #534

**Comment by c-knowles** [comment]
Sure yes my preference is same repo so docs update is in the same PR. However considering gitbook change requests I don't mind it being separate. If we combine there are a few updates we need to do. If you want it inside docs folder we may be able to generate GitHub website later once we have more time to work on site pieces.

**Comment by mumoshu** [comment]
@c-knowles What do you mean by "generate GitHub website"? Generate github pages from the contents of the `docs/` directory imported from `github.com/kube-aws/docs`?

**Comment by c-knowles** [comment]
@mumoshu I meant later it's possible to directly use github pages feature rather than gitbook. It would need more work as the default themes are not very useable for documentation. I don't mean to propose it for right now, purely that we are compatible using the same markdown. The URL if we ever used github pages for this repo would be `kubernetes-incubator.github.io/kube-aws/`.

**Comment by mumoshu** [comment]
@mikedanese Hi! Would you mind guiding us about how we could use an additional github app(gitbook for this specific case)?
It seems like we have lost connections with any of kubernetes-incubator admins who has privilege to do so.

**Comment by mikedanese** [comment]
Unfortunately I'm not even a member of the org even though I'm a sponsor of multiple projects

cc @sarahnovotny about privileges
cc @devin-donnelly since docs related

**Comment by sarahnovotny** [comment]
I have approved gitbook for kubernetes-incubator.

**Comment by c-knowles** [comment]
@mumoshu I've rebased this and synced up with that one master change that conflicted. If you'd like me to manually generate the docs into `gh-pages` branch I can do.

**Pull request merged**
