### PR TITLE
[v0.12.x] Flatcar

### PR DESCRIPTION
**Pull request by jorge07**
In this PR:

- Replace Flatcar for 0.12.x branch 
- Created ReleaseChannel model to keep logic outside config
- Introduces a cmd to get latests AmiID for the cluster.yaml configuration. Example:
```
➜ kube-aws ami
The Flatcar AmiId for region us-east-1 and release channel stable is different than the one in cluster definition.

Cluster.yaml:
- amiId: ami-04e51eabc8abea762
+ amiId: ami-011655f166912d5ba
```

### CODE REVIEW

**Comment by dominicgunn** [comment]
Hey @jorge07,

Is your team still actively using v0.12.x? I'm hesistant to merge & create a release unless you are.

**Comment by jorge07** [comment]
Yes we do. We've some clusters in 0.12.x where the upgrade to 0.13.x didn't end well, so we maintain 0.12.x branch.

**Comment by dominicgunn** [comment]
Got it, thanks for the PR.

**Pull request merged**
