### PR TITLE
Fixes #946 Support drop-ins in customSystemdUnits

### LINKED ISSUE #946: Support drop-ins in customSystemdUnits
I'd like to use drop-ins to modify existing systemd units, but the customSystemdUnits schema/template don't support them.

https://github.com/coreos/coreos-cloudinit/blob/master/Documentation/cloud-config.md#units

### PR DESCRIPTION
**Pull request by jeremyd**

### CODE REVIEW

**Comment by redbaron** [comment]
this enables drop-ins  for custom unit files, but original ticket was about extending existing ones

**Comment by jeremyd** [comment]
@redbaron, I'll ask him in the ticket.  Drop-ins as implemented here are capable of overriding other units that are not part of the customSystemdUnits configuration units.

**Comment by groner** [comment]
Hi @jeremyd,

From looking at the template, the new drop-ins section looks like it should do.

The top level content key isn't optional nor omitted from the templates currently.  Will that override an existing unit?

**Comment by jeremyd** [comment]
Good point, I will make this optional and then I think it won't override.
Will need to do a quick test as I haven't used these dropins much yet.

**Comment by jeremyd** [comment]
I made all the unit options 'optional' to properly support drop-ins as they were intended.  Then I tested that the override showed up on the docker.service itself.  Neat! Example test result below.

cluster.yaml.snippit:
```
  customSystemdUnits:
    - name: docker.service
      drop-ins:
        - name: 10-fast-restart.conf
          content: |
            [Service]
            Restart=always
            RestartSec=1s
```

resulting systemd unit config (on a test system)
```
~ $ sudo systemctl cat docker.service
# /run/systemd/system/docker.service
[Unit]
Requires=torcx.target
After=torcx.target
Description=Docker Application Container Engine
Documentation=http://docs.docker.com
After=containerd.service docker.socket network-online.target
Wants=network-online.target
Requires=containerd.service docker.socket

[Service]
EnvironmentFile=/run/metadata/torcx
Type=notify
EnvironmentFile=-/run/flannel/flannel_docker_opts.env
Environment=DOCKER_SELINUX=--selinux-enabled=true

# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/env PATH=${TORCX_BINDIR}:${PATH} ${TORCX_BINDIR}/dockerd --host=fd:// --containerd=/var/run/docker/libcontainerd/docker-containerd.sock $DO
ExecReload=/bin/kill -s HUP $MAINPID
LimitNOFILE=1048576
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process
# restart the docker process if it exits prematurely
Restart=on-failure
StartLimitBurst=3
StartLimitInterval=60s

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/docker.service.d/10-fast-restart.conf
[Service]
Restart=always
RestartSec=1s
```

**Comment by mumoshu** [comment]
@jeremyd Thanks for the contribution as always 👍

**Pull request merged**
