### PR TITLE
Check stack existence via DescribeStacks

### PR DESCRIPTION
**Pull request by c-knowles**
Rather than ListStacks without any paging.

Fixes https://github.com/kubernetes-incubator/kube-aws/issues/1479

### CODE REVIEW

**Comment by c-knowles** [comment]
@mumoshu do you know why I cannot request a review from @davidmccormick? I cannot get his user to appear on the reviewers list.

**Comment by mumoshu** [comment]
@c-knowles Thanks for the fix!

> do you know why I cannot request a review from @davidmccormick? I cannot get his user to appear on the reviewers list.

Just invited @davidmccormick as a collaborator w/ read/write privs to this repo, hoping it makes difference.

**Comment by c-knowles** [comment]
@davidmccormick we could implement that although then it does not mirror the SDK so not sure if it's worth it.

**Pull request merged**
