### PR TITLE
Allow reusing an existing autoscaling notification target

### LINKED ISSUE #771: Reusing an existing autoscaling notification target
Extracted from https://github.com/kubernetes-incubator/kube-aws/issues/747#issuecomment-314756229
cc @VinceMD @mclarke47

### PR DESCRIPTION
**Pull request by mumoshu**
Resolves #771

### CODE REVIEW

**Comment by redbaron** [comment]
Does node drainer work without specified notification target all together? If so we should remove it instead of making it customizable

**Comment by mumoshu** [comment]
@redbaron Thanks for the comment!
Would you mind taking a look into [my comment](https://github.com/kubernetes-incubator/kube-aws/issues/747#issuecomment-314984908)?

**Comment by redbaron** [comment]
Queue was used to make lifecycle hook happy. If it can now work without it, there is no need for the queue. I can see no meaningful way it can be used for debugging, as only user of the queue was ASG placing termination messages which are then never consumed. so only information you could extract from it is whether ASG wants instance to be terminated, you can get that info just by querying  asg status

**Comment by mumoshu** [comment]
@redbaron Thanks for the clarification.

> so only information you could extract from it is whether ASG wants instance to be terminated, you can get that info just by querying asg status

This did make sense to me 👍

**Comment by danielfm** [comment]
> Queue was used to make lifecycle hook happy. If it can now work without it, there is no need for the queue.

Exactly, it was not possible to create the ASG lifecycle hook via CloudFormation without a target SQS queue/SNS topic, so that's the only reason it exists.

**Comment by mumoshu** [comment]
@redbaron @danielfm Thanks! Closing this in favor of #780

**Pull request closed without merging**
