### PR TITLE
[v0.15.0] Switch CoreOS to Flatcar

### PR DESCRIPTION
**Pull request by flah00**
# Changes

* use Flatcar in the v0.15.x branch, shamelessly stolen from @jorge07 and @dominicgunn, thanks!

### CODE REVIEW

**Comment by jorge07** [comment]
You'll need to modify the unit for disabled auto updates. I've it in my 0.12 branch but need to prepare a PR

**Comment by flah00** [comment]
@jorge07 I am not familiar with the unit you're talking about. Can you fill me in?  :)

**Comment by jorge07** [comment]
Sure. Here the original pr #1241 and here the reference for the new OS https://docs.flatcar-linux.org/os/update-strategies/#disable-automatic-updates-daemon

**Comment by jorge07** [comment]
Great work!

**Comment by flah00** [comment]
Thanks for your help!

**Comment by dominicgunn** [comment]
Super sorry we missed this, thanks for contributing.

**Pull request merged**
