### PR TITLE
Bug/fix cf stack paging v0.11.x

### PR DESCRIPTION
**Pull request by c-knowles**
Check stack existence via DescribeStacks

### CODE REVIEW

**Comment by mumoshu** [comment]
@c-knowles I doubt this complicates commit history! How about cherry-picking beae9b71b25bff7c85539a4a23f5a05a3f022a2d, or even better squash three commits from beae9b71b25bff7c85539a4a23f5a05a3f022a2d to 0d678045dfd6876f9021afc11cdde087c7d04a24 into one and cherry-pick that?

**Comment by mumoshu** [comment]
And doing so would also avoid requiring k8s-ci-robot to sign the CLA 😉

**Comment by c-knowles** [comment]
@mumoshu I've cherry picked my 3 commits and force pushed over my branch, PR should be ready now.

**Comment by c-knowles** [comment]
I think this branch might need an update to the AWS SDK.

**Comment by davidmccormick** [comment]
Are you guys happy marking this with "approve" and the k8s-ci-robot merging it?  I wasn't expecting it to go ahead an automatically merge to *master* yesterday!  Would you rather have a more manual process?  Don't want to go start messing up your release processes! :)

**Comment by mumoshu** [comment]
@davidmccormick Thanks for reviewing! I'd personally prefer the `Squash and merge` button, so that the commit history becomes cleaner :)

**Comment by c-knowles** [comment]
@davidmccormick I wasn't expecting that either but I'm not fully familiar with the CI bot functions. @mumoshu will you squash and merge?

**Comment by mumoshu** [comment]
Done. Thanks for the fix ☺️

**Pull request merged**
