### PR TITLE
Correct semantic version checks

### LINKED ISSUE #1373: K8sVer check is invalid for kube-proxy
https://github.com/kubernetes-incubator/kube-aws/blob/master/core/controlplane/config/templates/cloud-config-controller#L3211

```
{{if ge .K8sVer "v1.9"}}kubeproxy.config.k8s.io{{else}}componentconfig{{end}}/v1alpha1
```

The syntax here does not work for 1.10 because of the string validation

This seems to work https://github.com/mcuadros/go-version 

PR proposal on its way

### PR DESCRIPTION
**Pull request by kevtaylor**
Fixes #1373

### CODE REVIEW

**Comment by c-knowles** [comment]
@kevtaylor there’s already the masterminds “semver” in use in the code checking for the reconciler, could we reuse the same to ensure dependencies are minimised?

**Comment by kevtaylor** [comment]
@c-knowles I'll take a look. I didn't appreciate something was already in place.

**Comment by kevtaylor** [comment]
@c-knowles @mumoshu Used semver instead

**Comment by mumoshu** [comment]
@kevtaylor Thanks for the contribution! Can you also revert `Gopkg.toml` and `Gopkg.lock`? My understanding was that you don't need extra dependencies for this fix.

**Comment by kevtaylor** [comment]
@mumoshu Apologies yes indeed. Submitted with reverted files

**Comment by kevtaylor** [comment]
@mumoshu Seems like something occurred in the e2e tests? How do we force a retest?

**Pull request merged**
