### PR TITLE
Fix dashboard version in labels and RC name

### PR DESCRIPTION
**Pull request by Vrtak-CZ**

### CODE REVIEW

**Comment by Vrtak-CZ** [comment]
Btw @mumoshu is there any reason for version in RC name for dashboard?

**Comment by mumoshu** [comment]
@Vrtak-CZ Nothing specific on my side - Even [the corresponding kube-dashboard manifest in the upstream repo](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dashboard/dashboard-controller.yaml) doesn't contain version numbers in its names.
I guess we can safely remove the version numbers if you'd (also) like to do so.

**Comment by Vrtak-CZ** [comment]
@mumoshu rebased and removed :-)

**Comment by mumoshu** [comment]
@Vrtak-CZ LGTM. Thanks for your support 👍

**Pull request merged**
