### PR TITLE
Fix quote on "Launch the secondary node"

### PR DESCRIPTION
**Pull request by velo**

### CODE REVIEW

**Comment by mumoshu** [comment]
Good catch, @velo!
I'll merge this asap after you signed the CLA.

**Comment by velo** [comment]
I'm trying to, but doesn't seem to be that simple

screen shot 2017-05-11 at 12 08 38 pm

**Comment by mumoshu** [comment]
@velo Thanks. The same access denied error appears to me, too 😅 
What do you see after navigating via the`My Account` link in your capture?
For me, it looks like:

image

and I wish you could see any link to sign the CLA there.

**Comment by velo** [comment]
Looks it's all good now, thanks

**Comment by mumoshu** [comment]
@velo Thanks for taking your time 👍

**Pull request merged**
