### PR TITLE
Introduce the rescheduler

### PR DESCRIPTION
**Pull request by c-knowles**
For https://github.com/coreos/kube-aws/issues/118.

- Currently using raw Pod as per [salt setup](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/rescheduler/rescheduler.manifest)
- Introduced `addons` section for components like this and future components mentioned in https://github.com/kubernetes-incubator/kube-aws/issues/118 (e.g. kube-state-metrics)
- Logging routed via standard streams, in the future we could support other log routing
- gcr image used, not sure if hyperkube has the rescheduler
- Aligned to https://github.com/kubernetes-incubator/kube-aws/pull/390 by allowing
image repo/tag to be overridden

### CODE REVIEW

**Comment by c-knowles** [comment]
@mumoshu this is not quite ready yet. I launched the previous PR on a cluster using an older version of kube-aws but I've since updates my clusters to the latest kube-aws and now rescheduler is crashing frequently and not sure why yet. I tried upgrading to `v0.3.0` but that also crashes. I'm going to debug that next.

**Comment by c-knowles** [comment]
@mumoshu this is not quite ready yet. I launched the previous PR on a cluster using an older version of kube-aws and it was working fine. However, I've since updated my clusters to the latest kube-aws and now rescheduler is crashing frequently and not sure why yet. I tried upgrading to v0.3.0 but that also crashes. I'm going to debug that next.

**Comment by c-knowles** [comment]
I had an initial look at this and it seems the rescheduler crashes if there is more than one running. I had a look around for any specific references to this as a requirement but didn't find much. Perhaps we should ask at the scheduling SIG. It's likely I will change this to a Deployment under `/srv` to get this running and then we can improve from there if needed.

**Comment by mumoshu** [comment]
AFAIK rescheduler doesn't involve leader election like kube-scheduler and kube-controller-manager do. Does it relate?
Can you collect log messages from one of crashing rescheduler pods by running `kubelctl logs --previous <primary container name of rescheduler pod>`?

**Comment by c-knowles** [comment]
Here are some:
```
✗ stern --since 1m --namespace=kube-system kube-rescheduler
+ kube-rescheduler-ip-10-0-100-127.eu-west-1.compute.internal › kube-rescheduler
+ kube-rescheduler-ip-10-0-102-141.eu-west-1.compute.internal › kube-rescheduler
kube-rescheduler-ip-10-0-100-127.eu-west-1.compute.internal kube-rescheduler panic: runtime error: invalid memory address or nil pointer dereference
kube-rescheduler-ip-10-0-100-127.eu-west-1.compute.internal kube-rescheduler [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x402031]
kube-rescheduler-ip-10-0-100-127.eu-west-1.compute.internal kube-rescheduler 
kube-rescheduler-ip-10-0-100-127.eu-west-1.compute.internal kube-rescheduler goroutine 1 [running]:
kube-rescheduler-ip-10-0-100-127.eu-west-1.compute.internal kube-rescheduler panic(0x1c509a0, 0xc42000a030)
kube-rescheduler-ip-10-0-100-127.eu-west-1.compute.internal kube-rescheduler 	/usr/local/google/home/pszczesniak/.gvm/gos/go1.7.5/src/runtime/panic.go:500 +0x1a1
kube-rescheduler-ip-10-0-100-127.eu-west-1.compute.internal kube-rescheduler main.createKubeClient(0xc4203103f0, 0x1fcb501, 0x1, 0x1, 0x0, 0x0)
kube-rescheduler-ip-10-0-100-127.eu-west-1.compute.internal kube-rescheduler 	/usr/local/google/home/pszczesniak/go/src/k8s.io/contrib/rescheduler/rescheduler.go:207 +0x61
kube-rescheduler-ip-10-0-100-127.eu-west-1.compute.internal kube-rescheduler main.main()
kube-rescheduler-ip-10-0-100-127.eu-west-1.compute.internal kube-rescheduler 	/usr/local/google/home/pszczesniak/go/src/k8s.io/contrib/rescheduler/rescheduler.go:100 +0x101
kube-rescheduler-ip-10-0-102-141.eu-west-1.compute.internal kube-rescheduler panic: runtime error: invalid memory address or nil pointer dereference
kube-rescheduler-ip-10-0-102-141.eu-west-1.compute.internal kube-rescheduler [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x402031]
kube-rescheduler-ip-10-0-102-141.eu-west-1.compute.internal kube-rescheduler 
kube-rescheduler-ip-10-0-102-141.eu-west-1.compute.internal kube-rescheduler goroutine 1 [running]:
kube-rescheduler-ip-10-0-102-141.eu-west-1.compute.internal kube-rescheduler panic(0x1c509a0, 0xc42000a030)
kube-rescheduler-ip-10-0-102-141.eu-west-1.compute.internal kube-rescheduler 	/usr/local/google/home/pszczesniak/.gvm/gos/go1.7.5/src/runtime/panic.go:500 +0x1a1
kube-rescheduler-ip-10-0-102-141.eu-west-1.compute.internal kube-rescheduler main.createKubeClient(0xc4204570e0, 0x1fcb501, 0x1, 0x1, 0x0, 0x0)
kube-rescheduler-ip-10-0-102-141.eu-west-1.compute.internal kube-rescheduler 	/usr/local/google/home/pszczesniak/go/src/k8s.io/contrib/rescheduler/rescheduler.go:207 +0x61
kube-rescheduler-ip-10-0-102-141.eu-west-1.compute.internal kube-rescheduler main.main()
kube-rescheduler-ip-10-0-102-141.eu-west-1.compute.internal kube-rescheduler 	/usr/local/google/home/pszczesniak/go/src/k8s.io/contrib/rescheduler/rescheduler.go:100 +0x101
```

**Comment by mumoshu** [comment]
Thanks.
Unfortunately, I have no idea how could a panic like that happen at https://github.com/kubernetes/contrib/blob/master/rescheduler/rescheduler.go#L207.

**Comment by c-knowles** [comment]
@mumoshu yes me neither that's why I needed to debug further. Are you happy enough switching this one to a Deployment?

**Comment by mumoshu** [comment]
Yes, if it works
2017年3月23日(木) 13:06 Chris Knowles <notifications@github.com>:

**Comment by c-knowles** [comment]
OK updated to Deployment. Successfully tested this setup in a dev cluster but as of yet I've been unable to get the e2e tests to complete execution, they generally fail on something else before they get to this part. @mumoshu are you able to help me out and run the e2e you mentioned in https://github.com/kubernetes-incubator/kube-aws/issues/118#issuecomment-264851226?

**Comment by c-knowles** [comment]
Some sample output:
```
✗ stern --since 1m --namespace=kube-system kube-rescheduler
+ kube-rescheduler-2055475-6msgd › kube-rescheduler
kube-rescheduler-2055475-6msgd kube-rescheduler I0323 04:49:38.701376       1 rescheduler.go:73] Running Rescheduler
kube-rescheduler-2055475-6msgd kube-rescheduler I0323 04:51:48.704278       1 rescheduler.go:114] Critical pod kube-system_kube-dns-782804071-rcs1r is unschedulable. Trying to find a spot for it.
kube-rescheduler-2055475-6msgd kube-rescheduler I0323 04:51:48.719924       1 rescheduler.go:128] Trying to place the pod on node ip-10-0-101-248.eu-west-1.compute.internal
kube-rescheduler-2055475-6msgd kube-rescheduler I0323 04:51:48.738340       1 rescheduler.go:258] Pod default_nginx-test-3661400916-sqc08 will be deleted in order to schedule critical pod kube-system_kube-dns-782804071-rcs1r.
kube-rescheduler-2055475-6msgd kube-rescheduler I0323 04:51:48.738651       1 event.go:216] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx-test-3661400916-sqc08", UID:"a5cff8f1-0f83-11e7-aed5-0a388ace2367", APIVersion:"v1", ResourceVersion:"8462", FieldPath:""}): type: 'Normal' reason: 'DeletedByRescheduler' Deleted by rescheduler in order to schedule critical pod kube-system_kube-dns-782804071-rcs1r.
kube-rescheduler-2055475-6msgd kube-rescheduler I0323 04:51:48.743308       1 rescheduler.go:258] Pod default_nginx-test-3661400916-tdv9w will be deleted in order to schedule critical pod kube-system_kube-dns-782804071-rcs1r.
kube-rescheduler-2055475-6msgd kube-rescheduler I0323 04:51:48.743522       1 event.go:216] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx-test-3661400916-tdv9w", UID:"b1692eb3-0f83-11e7-aed5-0a388ace2367", APIVersion:"v1", ResourceVersion:"8735", FieldPath:""}): type: 'Normal' reason: 'DeletedByRescheduler' Deleted by rescheduler in order to schedule critical pod kube-system_kube-dns-782804071-rcs1r.
kube-rescheduler-2055475-6msgd kube-rescheduler I0323 04:51:48.763289       1 rescheduler.go:258] Pod default_nginx-test-3661400916-w7g31 will be deleted in order to schedule critical pod kube-system_kube-dns-782804071-rcs1r.
kube-rescheduler-2055475-6msgd kube-rescheduler I0323 04:51:48.763533       1 event.go:216] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx-test-3661400916-w7g31", UID:"fd6ee1ee-0f83-11e7-aed5-0a388ace2367", APIVersion:"v1", ResourceVersion:"9625", FieldPath:""}): type: 'Normal' reason: 'DeletedByRescheduler' Deleted by rescheduler in order to schedule critical pod kube-system_kube-dns-782804071-rcs1r.
kube-rescheduler-2055475-6msgd kube-rescheduler I0323 04:51:48.777847       1 rescheduler.go:147] Waiting for pod kube-system_kube-dns-782804071-rcs1r to be scheduled
kube-rescheduler-2055475-6msgd kube-rescheduler I0323 04:52:03.795646       1 rescheduler.go:159] Pod kube-system_kube-dns-782804071-rcs1r was successfully scheduled.
kube-rescheduler-2055475-6msgd kube-rescheduler I0323 04:52:08.778525       1 rescheduler.go:204] Releasing taint {Key:CriticalAddonsOnly Value:kube-system_kube-dns-782804071-rcs1r Effect:NoSchedule} on node ip-10-0-101-248.eu-west-1.compute.internal
kube-rescheduler-2055475-6msgd kube-rescheduler I0323 04:52:08.785098       1 rescheduler.go:222] Successfully released all taints on node ip-10-0-101-248.eu-west-1.compute.internal
```

**Comment by mumoshu** [comment]
@c-knowles Could you run e2e with:

env vars:

```
export KUBE_AWS_KEY_NAME=<your ec2 key pair name>
export SSH_PRIVATE_KEY=<local file path to your ssh private key matching the ec2 key pair>
export KUBE_AWS_KMS_KEY_ARN=arn:aws:kms:<region>:<account>:key/<key id>
export KUBE_AWS_DOMAIN=<your domain>
export KUBE_AWS_REGION=<your region>
export KUBE_AWS_AVAILABILITY_ZONE=<your az 1>
export KUBE_AWS_HOSTED_ZONE_ID=<your hosted zone id matching domain>
export KUBE_AWS_S3_DIR_URI=s3://<your buckt name>
export KUBE_AWS_SSH_KEY=/path/to/your/ssh/private/key
export KUBE_AWS_AZ_1=<your az 1>

export DOCKER_REPO=quay.io/mumoshu/
```

and command:

```
$ KUBE_AWS_CLUSTER_NAME=kubeawstest1 ./run all
```

?

**Comment by redbaron** [comment]
> Unfortunately, I have no idea how could a panic like that happen at https://github.com/kubernetes/contrib/blob/master/rescheduler/rescheduler.go#L207.

Submitted PR with a fix: https://github.com/kubernetes/contrib/pull/2490

**Comment by mumoshu** [comment]
Good job!
2017年3月23日(木) 22:03 Maxim Ivanov <notifications@github.com>:

**Comment by c-knowles** [comment]
@redbaron on HA controllers all instances were crashing, does the fix patch the crash or will both reschedulers run ok? I mean should I change it back to controller pod rather than deployment?

**Comment by c-knowles** [comment]
@mumoshu I'm trying that command again but it's pretty much what I've been running apart from a couple of new keys. Currently getting this so many need some help tracking this one down:
```
+ /Users/cknowles/Projects/go//src/github.com/coreos/kube-aws/bin/kube-aws validate --s3-uri s3://OBFUSCATED/kubeawstest1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa9bdb]

goroutine 1 [running]:
panic(0x7b0e20, 0xc4200141b0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/coreos/kube-aws/core/controlplane/config.CachedEncryptor.EncryptedCredentialFromPath(0xc42001b310, 0x4b, 0xddb2c0, 0xc420534040, 0xc4203e52c0, 0x12, 0xa, 0xc420564240, 0xc4203b8cc0)
	/Users/cknowles/Projects/go/src/github.com/coreos/kube-aws/core/controlplane/config/credential.go:40 +0x13b
github.com/coreos/kube-aws/core/controlplane/config.ReadOrEncryptTLSAssets(0x8bdfd6, 0xb, 0xc42001b310, 0x4b, 0xddb2c0, 0xc420534040, 0x8ba2a3, 0x3, 0x0)
	/Users/cknowles/Projects/go/src/github.com/coreos/kube-aws/core/controlplane/config/tls_config.go:278 +0x373
github.com/coreos/kube-aws/core/controlplane/config.ReadOrCreateEncryptedTLSAssets(0x8bdfd6, 0xb, 0xc420160e50, 0xe, 0x0
```

**Comment by mumoshu** [comment]
Sorry for the inconvenience but the panic caused by a bug seems to be
shadowing the actual problem. AFAICS, you seem to have an error while
encrypting one of your cert pem files. For example, is your kms key arn
passed via env var correct? One of your certs is larger than 4kb?

Anyway, I'll fix the bug to stop panicing and show an actual error in your
case! Then, debugging would be much easier.
2017年3月23日(木) 23:57 Chris Knowles <notifications@github.com>:

**Comment by mumoshu** [comment]
The panic is fixed in #452

**Comment by mumoshu** [comment]
@c-knowles In addition to the command explained above, perhaps you could pass `FOCUS=.*Rescheduler.*` for running test cases related to only rescheduler.

```
$ FOCUS=.*Rescheduler.* KUBE_AWS_CLUSTER_NAME=kubeawstest1 ./run all
```

`FOCUS` is the word from gingko which is meant to be a filter to selectively run test cases.

**Comment by c-knowles** [comment]
@mumoshu no problem, I'll try to re-run this shortly.

**Comment by c-knowles** [comment]
After a few round of bug fixing to the e2e tests, I finally got this:
```
2017/03/24 04:02:03 e2e.go:722: Running: Ginkgo tests

Mar 24 04:02:04.138: INFO: Waiting up to 4h0m0s for all (but 0) nodes to be schedulable
Mar 24 04:02:04.177: INFO: Waiting up to 10m0s for all pods (need at least 0) in namespace 'kube-system' to be running and ready
Mar 24 04:02:04.181: INFO: Waiting for pods to enter Success, but no pods in "kube-system" match label map[name:e2e-image-puller]
Mar 24 04:02:04.191: INFO: 14 / 14 pods in namespace 'kube-system' are running and ready (0 seconds elapsed)
Mar 24 04:02:04.191: INFO: expected 5 pod replicas in namespace 'kube-system', 5 are Running and Ready.
Mar 24 04:02:04.194: INFO: Waiting for pods to enter Success, but no pods in "kube-system" match label map[name:e2e-image-puller]
Mar 24 04:02:04.194: INFO: Dumping network health container logs from all nodes
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
[k8s.io] Rescheduler [Serial] 
  should ensure that critical pod is scheduled in case there is no resources available
  /go/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/rescheduler.go:69
[BeforeEach] [k8s.io] Rescheduler [Serial]
  /go/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:141
STEP: Creating a kubernetes client
Mar 24 04:02:04.201: INFO: >>> kubeConfig: /kube-temp/kubeconfig

STEP: Building a namespace api object
STEP: Waiting for a default service account to be provisioned in namespace
[BeforeEach] [k8s.io] Rescheduler [Serial]
  /go/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/rescheduler.go:47
Mar 24 04:02:04.223: INFO: Only supported for providers [gce gke] (not skeleton)
[AfterEach] [k8s.io] Rescheduler [Serial]
  /go/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:142
Mar 24 04:02:04.224: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
STEP: Destroying namespace "e2e-tests-rescheduler-dxd39" for this suite.
Mar 24 04:02:14.284: INFO: namespace: e2e-tests-rescheduler-dxd39, resource: bindings, ignored listing per whitelist

S [SKIPPING] in Spec Setup (BeforeEach) [10.107 seconds]
[k8s.io] Rescheduler [Serial]
/go/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:826
  should ensure that critical pod is scheduled in case there is no resources available [BeforeEach]
  /go/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/rescheduler.go:69

  Mar 24 04:02:04.223: Only supported for providers [gce gke] (not skeleton)

  /go/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:287
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 0 of 474 Specs in 10.182 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 474 Skipped PASS

Ginkgo ran 1 suite in 10.425911512s
Test Suite Passed
2017/03/24 04:02:14 e2e.go:724: Step 'Ginkgo tests' finished in 10.701995831s
```

So it skips it 🤣 . Source seems to [just support gke/gce now](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/scheduling/rescheduler.go#L44). I guess if we want to have this test we'd need to support AWS there.

**Comment by mumoshu** [comment]
Oh my gosh 😭 Thanks for your efforts...

OK then, how about merging this without passing the rescheduler E2E test cases, and see how it works in the wild? 😃 

The code LGTM. Are you ready for merging this?

// It is optional but are you willing to add a test case to `test/integration/maincluster_test.go` for validating json when this feature is enabled?

**Comment by c-knowles** [comment]
I think the older version of the e2e test did not have this skip and I had not checked the recent versions until now.

I'm happy enough merging but let me have a look at adding to the integration test cases first.

**Comment by c-knowles** [comment]
@mumoshu added those, I'm not sure if there is a more sustainable way to add validation to each model. I was looking around for YAML schema tech but did not find much. JSON schema is available, I know some tools are converting first and them validating (I heard kubectl does this for example and found [this](https://github.com/kubernetes/kubernetes/blob/b9e3742779ac4c37f12c2ab2bb387c37eab364e0/pkg/kubectl/cmd/util/jsonmerge/jsonmerge.go#L139)).

**Comment by mumoshu** [comment]
@c-knowles Thanks for your effort!
Though adding such validations requires verbose code, I'm rather happy with the current solution because it just work.

**Comment by c-knowles** [comment]
By the way, Kubernetes 1.6 needs rescheduler 0.3.0+. Happy to merge this in but going to work on checking the upgrade functions ok shortly.

**Comment by mumoshu** [comment]
I'm ok to merge this but if you'd like to, I suggest adding:

```yaml
addons:
  rescheduler:
    enabled: true
```

to the lengthy `WithExperimentalFeatures` test-case in the `maincluster_test.go`, so that it can test each commit to verify generated cloud-configs and stack templates are not broken badly when the rescheduler is enabled.
It is also ok for me if you'd like an another `context` rather than `WithExperimentalFeatures`, dedicated for testing the `addons.rescheduler.enabled` flag.

**Comment by mumoshu** [comment]
As code LGTM, I'm merging this early so that we don't suffer from conflicts.
Thanks for your contribution @c-knowles!

**Pull request merged**
