### PR TITLE
Update various components version.

### PR DESCRIPTION
**Pull request by camilb**
**Updates:**
* kubernetes - v1.7.8
* flannel - v0.9.0
* calico - v2.6.1
* cluster-autoscaler - v0.6.2
* etcd - v3.2.9
* cluster-proportional-autoscaler v1.1.2
* kube2iam - v0.8.1
* heapster - v1.4.3
* kube-dns-1.14.6
* addon-resizer - v2.1
* tiller - v2.6.2

**Changes:**
* **Calico Policy Controller renamed to Calico Kube Controllers** [more-info](https://github.com/projectcalico/kube-controllers/commit/11feb595bfadf4b1f1b2a57dcf99af59b4b29c94)

* **Kubernetes Dashboard is exposed only over https and requires authentication using Kubeconfig or a token.**

Example creating a cluster administrator token

    * create a  service account and clusterrolebinding for kubernetes dashboard admin
    kubectl create serviceaccount kubedashadmin -n kube-system
    kubectl create clusterrolebinding kubedashadmin --clusterrole=cluster-admin --serviceaccount=kube-system:kubedashadmin

    * get token
    KUBEDASHADMIN_TOKEN=$(kubectl get secrets --namespace=kube-system | grep kubedashadmin-token| cut -d ' ' -f 1)
    kubectl get secret $KUBEDASHADMIN_TOKEN -o 'jsonpath={.data.token}' -n kube-system | base64 --decode

**Conformance tests available here:**
https://scanner.heptio.com/b4e4e723911bf037b62ea70151ecc1a9/diagnostics/

Updated for commit [e18784f](https://github.com/kubernetes-incubator/kube-aws/pull/962/commits/e18784f9ad6a2fe3734592e847854c550c505a56) except kubernetes 1.7.8 (hyperrkube not yet released by CoreOS)
https://scanner.heptio.com/1251e49fcd3957ed19b0c2e44549491e/diagnostics/

### CODE REVIEW

**Comment by danielfm** [comment]
Great! Loved the idea of using the Heptio scanner. Well done!

**Comment by redbaron** [comment]
I'd take dashboard 1.7.x update out of this until we have recommended RBAC policy for it

**Comment by camilb** [comment]
Removed the Dashboard 1.7.X for now. I'll test the [recommended deployment](https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml) soon.

**Comment by danielfm** [comment]
I updated my current cluster with all changes introduced here, except for the `calico-kube-controllers` one, and everything is running as expected.

**Comment by danielfm** [comment]
Can you change this to Kubernetes 1.7.8 instead?

It just got released with a potential fix for the dreaded #598. 🎉

**Comment by camilb** [comment]
> Can you change this to Kubernetes 1.7.8 instead?
 It just got released with a potential fix for the dreaded #598. 🎉

I'll update it as soon as CoreOS releases the hyperkube for v1.7.8

**Comment by c-knowles** [comment]
@redbaron shall we get this one merged?

**Comment by camilb** [comment]
@c-knowles We have to wait for the hyperkube 1.7.8 release from CoreOS (I hope it will be released today). I'm also testing Kubernetes dashboard v1.7.1 with RBAC and authentication.

**Comment by c-knowles** [comment]
Ah sorry I had interrupted your new commit as there now being a hyperkube build!

**Comment by danielfm** [comment]
@camilb awesome!

**Comment by redbaron** [comment]
My only problem with new Dashboard is that it is not like-for-like to what it was before. Unless we give dashboard account cluster-admin perms, new dashboard can come as a surprise, at least for our cluster users.

@camilb what do you think about extracting Dashboard changes into separate PR, then rest can be merged straight away

**Comment by camilb** [comment]
@redbaron No problem, I'll create a separate PR for the dashboard.

**Comment by redbaron** [comment]
can't be merged until 1.7.8 coreos is published :)

**Comment by camilb** [comment]
Yes, I think [v1.7.8+coreos.0](https://github.com/coreos/kubernetes/releases/tag/v1.7.8%2Bcoreos.0) was released during the quay outage and the build failed to push to quay. We'll wait.

**Comment by camilb** [comment]
@redbaron [v1.7.8+coreos.0](https://quay.io/repository/coreos/hyperkube?tab=tags) is now available https://github.com/coreos/kubernetes/issues/170

**Comment by mumoshu** [comment]
@camilb @redbaron @c-knowles @danielfm Thanks a lot for your efforts :+1:
I'm merging this.

Btw, I'm considering to cut kube-aws v0.9.9-rc.1 shortly after this. It has been a while since the last release and seems like there are many enough changes that will result in a meaningful release :wink:
WDYT?

**Pull request merged**
