### PR TITLE
V0.11.x configurable dashboard replicas

### PR DESCRIPTION
**Pull request by kylehodgetts**

### CODE REVIEW

**Comment by mumoshu** [comment]
@kylehodgetts Thanks for the improvement! This looks good. Would you mind submitting this against the master branch as well?

**Comment by kylehodgetts** [comment]
@mumoshu Here is the master PR #1539 Already merged

Also here is the v0.12.x PR: #1543

**Comment by davidmccormick** [comment]
I already reviewed and merged the `master` version of this change - thanks Kyle.

**Pull request merged**
