### PR TITLE
Etcd version

### PR DESCRIPTION
**Pull request by paalkr**
Change how etcd versions are specified, to resemble etcd project releases.

### CODE REVIEW

**Comment by davidmccormick** [comment]
Would you be able to cherry-pick this fix and PR for the v0.13.x and v0.14.x branch for me?

**Comment by paalkr** [comment]
I can try, but I'm not a git expert. Will it be sufficient to create PRs in the 0.13.x and 0.14.x branches?

**Comment by dominicgunn** [comment]
Nice eyes guys, thanks for spotting this @paalkr.

**Comment by davidmccormick** [comment]
Hi, no problem, I can do it tomorrow! :)

**Comment by davidmccormick** [comment]
Many thanks for your contribution! 🙏

**Pull request merged**
