### PR TITLE
Bump golang to v1.14.3

### PR DESCRIPTION
**Pull request by chenrui333**
- designate go.mod with v1.14
- bump travis to use go 1.14

### CODE REVIEW

**Comment by dominicgunn** [comment]
Thanks for the PR! Master is now going to be for the v.1.17.x cut, could you also contribute the same patch for our v1.16.x branch?

**Comment by chenrui333** [comment]
> Thanks for the PR! Master is now going to be for the v.1.17.x cut, could you also contribute the same patch for our v1.16.x branch?

sure thing

**Comment by chenrui333** [comment]
Somehow I could not find the v1.16 branch.

**Pull request merged**
