### PR TITLE
Fix for #1823

### PR DESCRIPTION
**Pull request by sei-nicolas**
This changes cluster.yaml initial skeleton to avoid the use of (not available) Config struct

### CODE REVIEW

**Comment by sei-nicolas** [comment]
[Signed CLA]

**Comment by davidmccormick** [comment]
Hi it's still not coming up as signed - can you take another look at signing it?  Many thanks!

**Comment by davidmccormick** [comment]
Can you also alter your commit message to remove the fixes #1823 from it?  This isn't allowed by our repository manager bot, sorry!

**Comment by sei-nicolas** [comment]
Sorry for the CLA, I had missed one step.

And changed for the commit text (I had actually tried to use the template in https://github.com/kubernetes-incubator/kube-aws/blob/master/CONTRIBUTING.md and could not understand what was the rejected character)

Hope that works.

**Comment by davidmccormick** [comment]
This looks great thanks!  Thanks very much for working on this issue and solution! 🙏 Would you please also PR your commit against out v0.15.x branch please?  Then I'll create a release containing your fix - many thanks!

**Comment by sei-nicolas** [comment]
Sure, PR 1827.

**Pull request merged**
