### PR TITLE
Fix for rpc-statd.service needed to mount NFS file shares

### PR DESCRIPTION
**Pull request by paalkr**
The rpc-statd.service is only startet if an EFS share is specified in the cluster.yaml. The rpc-statd.service is needed to successfully mount NFS file shares as part of POD specs. So without a EFS file share specified in the cluster.yaml you would not be able to munt any other not EFS NFS shares in your PODs.

Example that would not work without this fix

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfsmount
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nfsmount
    spec:
      volumes:            
      - name: nfsserver
        nfs:
          server: my.nfsserver.host
          path: /vol1
      containers:
      - name: busybox
        image: busybox
        volumeMounts:                        
        - mountPath: /vol1
          name: nfsserver 
```

Reference:
https://github.com/kubernetes-incubator/kube-aws/issues/1364
https://github.com/coreos/bugs/issues/2038

### CODE REVIEW

**Comment by mumoshu** [comment]
Something is wrong with the cloud-config rendering: `2018/06/18 00:23:10 Bad cloud-config:-`

**Comment by mumoshu** [comment]
I'm now trying to understand what this means :)

```
--- FAIL: TestRenderStackTemplate (0.13s)
	assertions.go:247: 
                          
	Error Trace:	cluster_test.go:723
		
	            	
			helper.go:120
		
	            	
			helper.go:41
		
	            	
			cluster_test.go:714
		
	Error:      	Received unexpected error:
		
	            	failed to render controller cloud config: cloud-config validation errors:
		
	            	line 166: error: found a tab character where an intendation space is expected
```

**Comment by mumoshu** [comment]
c9063bc should fix it

**Comment by paalkr** [comment]
@mumoshu Sorry for making that noob mistake :O I'm aware of tabs braking the templates, I thought I had used only white spaces. Well, all good now. I have been running with this modifications for a while and all seems to work as expected.

Any objections about merging this pull request?

**Comment by mumoshu** [comment]
> Any objections about merging this pull request?

@paalkr No! I was just waiting for the travis build to complete. Thanks for your contribution 🎉

**Comment by paalkr** [comment]
Thx, looking forward to the 0.11 release :)

**Pull request merged**
