### PR TITLE
[v0.14.x] Adds 'disable' flag for kubedns

### PR DESCRIPTION
**Pull request by brandong954**

### CODE REVIEW

**Comment by dominicgunn** [comment]
Hey @brandong954,

Thanks for the contribution. So that we can effectively track all the changes into the project could we cut the go.mod & go.sum changes from this PR, and if we want to add them upstream open a new PR to address dependency updates?

Cheers!

**Review by dominicgunn — COMMENTED** [review]
This seems mostly fine, except it won't remove deployments already installed, e.x. Having this enabled & changing it to disabled later won't turn off coredns.

**Review by dominicgunn — APPROVED** [review]

**Comment by dominicgunn** [comment]
/lgtm

Thanks for the contribution @brandong954

**Comment by brandong954** [comment]
Ah, thanks! Not completely working yet though ...

**Pull request merged**
