### PR TITLE
Initialize Config.AuthTokensConfig

### PR DESCRIPTION
**Pull request by jollinshead**
If we set
```
ManageCertificates: false
```
the method ```HasTokens``` is not resolvable to evaluate the expression
```
{{ if .AuthTokensConfig.HasTokens }}
```
since the ```AuthTokensConfig``` type is not initialised.

_Error message:_
```
executing "userdata/cloud-config-controller" at <.AuthTokensConfig.Ha...>: can't evaluate field HasTokens in type *config.CompactAuthTokens
```

**Fix implemented**: put the initialization of the auth token file asset outside of that ```if c.ManageCertificates```

### CODE REVIEW

**Comment by jollinshead** [comment]
https://github.com/kubernetes-incubator/kube-aws/issues/469

**Comment by danielfm** [comment]
Thanks for your report, @jollinshead! I'm the one to blame for this silly bug. 😓 

This is not the best way to fix this, though. The error here is that I put the initialization of the auth token file asset inside of that `if c.ManageCertificates`, which is wrong (the auth token file has nothing to do with this flag).

So the proper way to fix this is doing this instead:

```patch
diff --git a/core/controlplane/config/config.go b/core/controlplane/config/config.go
index a1b5cd4..10c26da 100644
--- a/core/controlplane/config/config.go
+++ b/core/controlplane/config/config.go
@@ -728,13 +728,29 @@ func (c Cluster) StackConfig(opts StackTemplateOptions) (*StackConfig, error) {
 		return nil, err
 	}
 
-	// TODO: Check if new tests are needed to verify the auth token file is handled correctly
+	var compactAssets *CompactTLSAssets
+	var compactAuthTokens *CompactAuthTokens
+
+	if c.AssetsEncryptionEnabled() {
+		compactAuthTokens, err = ReadOrCreateCompactAuthTokens(opts.AssetsDir, KMSConfig{
+			Region:         stackConfig.Config.Region,
+			KMSKeyARN:      c.KMSKeyARN,
+			EncryptService: c.ProvidedEncryptService,
+		})
+		if err != nil {
+			return nil, err
+		}
+		stackConfig.Config.AuthTokensConfig = compactAuthTokens
+	} else {
+		rawAuthTokens, err := ReadOrCreateUnecryptedCompactAuthTokens(opts.AssetsDir)
+		if err != nil {
+			return nil, err
+		}
+		stackConfig.Config.AuthTokensConfig = rawAuthTokens
+	}
 
 	if c.ManageCertificates {
 		if c.AssetsEncryptionEnabled() {
-			var compactAssets *CompactTLSAssets
-			var compactAuthTokens *CompactAuthTokens
-
 			compactAssets, err = ReadOrCreateCompactTLSAssets(opts.AssetsDir, KMSConfig{
 				Region:         stackConfig.Config.Region,
 				KMSKeyARN:      c.KMSKeyARN,
@@ -743,31 +759,13 @@ func (c Cluster) StackConfig(opts StackTemplateOptions) (*StackConfig, error) {
 			if err != nil {
 				return nil, err
 			}
-
-			compactAuthTokens, err = ReadOrCreateCompactAuthTokens(opts.AssetsDir, KMSConfig{
-				Region:         stackConfig.Config.Region,
-				KMSKeyARN:      c.KMSKeyARN,
-				EncryptService: c.ProvidedEncryptService,
-			})
-			if err != nil {
-				return nil, err
-			}
-
 			stackConfig.Config.TLSConfig = compactAssets
-			stackConfig.Config.AuthTokensConfig = compactAuthTokens
 		} else {
 			rawAssets, err := ReadOrCreateUnecryptedCompactTLSAssets(opts.AssetsDir)
 			if err != nil {
 				return nil, err
 			}
-
-			rawAuthTokens, err := ReadOrCreateUnecryptedCompactAuthTokens(opts.AssetsDir)
-			if err != nil {
-				return nil, err
-			}
-
 			stackConfig.Config.TLSConfig = rawAssets
-			stackConfig.Config.AuthTokensConfig = rawAuthTokens
 		}
 	}
 

```

**Comment by jollinshead** [comment]
@danielfm I've amended the pull request to reflect these changes

**Comment by danielfm** [comment]
@jollinshead The test seem to have failed due to a flake, try pushing an empty commit later to trigger another build, and hopefully this one will pass.

/cc @mumoshu

**Comment by jollinshead** [comment]
@danielfm Done

**Comment by danielfm** [comment]
@jollinshead before a maintainer can merge your PR, don't forget to sign the CLA.

**Comment by jollinshead** [comment]
@k8s-ci-robot "I signed it!"

**Comment by mumoshu** [comment]
Thanks @jollinshead and @danielfm - LGTM 👍

**Pull request merged**
