### PR TITLE
Make cluster-autoscaler resource request/limit configurable

### PR DESCRIPTION
**Pull request by Luke-Humphreys**
## What
We've exposed the cluster-autoscaler deployment resources and made them configurable via cluster.yaml using the same approach taken regarding the kube-dashboard

## Why
We've started to experience OOM issues & CPU throttling in our bigger environments.

### CODE REVIEW

**Comment by davidmccormick** [comment]
Any joy with those tests?

**Comment by Luke-Humphreys** [comment]
> Any joy with those tests?

@davidmccormick  It's getting there, I've found the root cause, working on the solution now

**Comment by davidmccormick** [comment]
Thank you for your contribution! 🙏

**Pull request merged**
