### PR TITLE
Add support for S3 buckets with the default encryption enabled

### LINKED ISSUE #831: Provide support for encrypted State buckets
Currently kube-aws gets a 403 when using a bucket with encryption enforced. Should be able to support buckets with encryption policy (KMS/AES256)

### PR DESCRIPTION
**Pull request by mumoshu**
Resolves #831
Depends on #1021 

Please see [the second commit](https://github.com/kubernetes-incubator/kube-aws/pull/1023/commits/88dd6511a1d81cc4583c7c0e5ef6587102599109) for reviewing changes independently from the PR this is dependent on.

### CODE REVIEW

**Comment by mumoshu** [comment]
I've verified this to work by updating my cluster with `kube-aws update --s3-uri s3://my-bucket-with-awskms-as-default-encryption` and then `kube-aws update --s3-uri s3://my-bucket-with-aes256-as-default-encryption`.

FYI, S3 buckets can be configured with the default encryption of `awskms` by e.g. checking this option on the console:

image

The "AES-256" option on the console corresponds to `AES256`.

Even though kube-aws doesn't explicitly set any value for the `x-amz-server-side-encryption` header, the S3 objects uploaded by kube-aws were encrypted as expected:

image

**Comment by danielfm** [comment]
Will unencrypted buckets continue to work after this change? Did you test that scenario as well?

**Comment by mumoshu** [comment]
@danielfm Thanks for pointing that out! I just tested that scenario and everything went well.
Basically, we can switch unencrypted/encrypted buckets anytime by running `kube-aws update` with different `s3-uri`s.

**Comment by mumoshu** [comment]
@danielfm Thanks for reviewing!

**Pull request merged**
