### PR TITLE
Bug/fix cf stack paging v0.12.x

### PR DESCRIPTION
**Pull request by c-knowles**

### CODE REVIEW

**Comment by c-knowles** [comment]
@mumoshu merge and release a patch for this? Were there any other patches so far relevant for 0.12.x?

**Comment by mumoshu** [comment]
@c-knowles I'm considering to merge #1484 as well before cutting v0.11.2.

v0.12.0 would contain #1473.

**Comment by mumoshu** [comment]
@c-knowles Thanks for the fix!

**Pull request merged**
