### PR TITLE
Integrate s3-uri flag into cluster.yml

### PR DESCRIPTION
**Pull request by jorge07**
Integrates `--s3-uri` flag into the cluster.yaml. Only `init` command require this flag now.

I'm not a go expert, so, help wanted here ;)

### CODE REVIEW

**Comment by jorge07** [comment]
Related https://github.com/kubernetes-incubator/kube-aws/issues/326

**Comment by mumoshu** [comment]
@jorge07 Awesome! I'm really glad you picked this up 👍 
Code LGTM. One thing - were you able to run `kube-aws up`, `validate` and then `update` successfully? (Out tests don't cover running those commands, unfortunately 😢)

**Comment by jorge07** [comment]
I didn't try yet as I was expecting some code changes but I'll try it and post results here.

**Comment by jorge07** [comment]
Doc pending.

**Comment by mumoshu** [comment]
Thanks!

Which e2e?
If you're referring to the e2e/run script included in this project, we're about to abandon it in favor of [sonobuoy](https://scanner.heptio.com/). It is easier to run, and more reliable way to run conformance tests on your cluster today 😄

**Comment by jorge07** [comment]
Ok!

**Comment by mumoshu** [comment]
@jorge07 Thanks, the doc update LGTM 👍 
I'll merge this once the [manual test](https://github.com/kubernetes-incubator/kube-aws/pull/1177#issuecomment-371800847) went well on your machine.

**Comment by jorge07** [comment]
Great. @mumoshu I'll try to do the manual testing on Monday

**Comment by mumoshu** [comment]
@jorge07 This is a friendly reminder that I'm awaiting the time we could merge this 😄

**Comment by jorge07** [comment]
Rebased for QA

**Comment by jorge07** [comment]
**QA Resume**

[cluster.yaml](https://gist.github.com/jorge07/b2457c6abd1fce6fb7477eb3ce2b1bc1)

Command | Result
---------- | -------------
`kube-aws init`      | OK
`kube-aws render` |  OK
`kube-aws validate`| OK
`kube-aws up` | OK
`kube-aws update` | OK
`kube-aws destroy` | OK



## Details

### Init
```sh
➜  cluster-test git:(s3-uri) ✗ ../bin/kube-aws init --s3-uri=s3://kube-aws-master/demo \
--external-dns-name=XXXX.porntube.com \
--region=eu-west-1 \
--availability-zone=eu-west-1a \
--key-name=XXXX \
--kms-key-arn="arn:aws:kms:us-east-1:XXXXXXX" \
--cluster-name=demo \
--hosted-zone-id=XXXXXXXX
```
### Render
```sh
➜  cluster-test git:(s3-uri) ✗ ../bin/kube-aws render
...
Success! Stack rendered to ./stack-templates.

Next steps:
1. (Optional) Validate your changes to cluster.yaml with "kube-aws validate"
2. (Optional) Further customize the cluster by modifying templates in ./stack-templates or cloud-configs in ./userdata.
3. Start the cluster with "kube-aws up".
```
### Validate
```sh
➜  cluster-test git:(s3-uri) ✗ ../bin/kube-aws validate
...

Validation OK!
```
### Up
```sh
➜  cluster-test git:(s3-uri) ✗ ../bin/kube-aws up
Creating AWS resources. Please wait. It may take a few minutes.
Streaming CloudFormation events for the cluster 'demo'...
Success! Your AWS resources have been created:
Cluster Name:           demo
Controller DNS Names:   YYYYYYY.eu-west-1.elb.amazonaws.com

The containers that power your cluster are now being downloaded.

You should be able to access the Kubernetes API once the containers finish downloading.
```
### Namespaces
```sh
➜  cluster-test git:(s3-uri) ✗ KUBECONFIG=kubeconfig kubectl get ns
NAME          STATUS    AGE
default       Active    7m
kube-public   Active    7m
kube-system   Active    7m
```
### All pods in kube-system should be running
```sh
➜  cluster-test git:(s3-uri) ✗ KUBECONFIG=kubeconfig kubectl get po -n kube-system
NAME                                                              READY     STATUS    RESTARTS   AGE
heapster-7f977f75f7-rg94f                                         2/2       Running   0          6m
kube-apiserver-ip-10-0-0-23.eu-west-1.compute.internal            1/1       Running   0          12m
kube-controller-manager-ip-10-0-0-23.eu-west-1.compute.internal   1/1       Running   0          12m
kube-dns-autoscaler-c895d6bbd-gmmm6                               1/1       Running   0          13m
kube-dns-d87fdd65-277h5                                           3/3       Running   0          6m
kube-dns-d87fdd65-996fk                                           3/3       Running   0          13m
kube-proxy-9fmdc                                                  1/1       Running   0          7m
kube-proxy-rkl5g                                                  1/1       Running   0          13m
kube-scheduler-ip-10-0-0-23.eu-west-1.compute.internal            1/1       Running   0          12m
kubernetes-dashboard-6ff488bcdd-hcbdz                             1/1       Running   0          13m
tiller-deploy-8698c78577-t2qkt                                    1/1       Running   0          13m
```

### Update worker pool 

In cluster.yaml
```
- #       instanceType: t2.medium
+       instanceType: t2.large
```

```sh
➜  cluster-test git:(s3-uri) ✗ ../bin/kube-aws update
Streaming CloudFormation events for the cluster 'demo'...
+00:00:00       UPDATE_IN_PROGRESS                      demo                    "User Initiated"
+00:00:03       UPDATE_IN_PROGRESS                      Controlplane
+00:00:05       UPDATE_COMPLETE                         Controlplane
......etc etc 
+00:02:52       Nodepool1       DELETE_IN_PROGRESS                      WorkersLC
+00:02:52       Nodepool1       DELETE_COMPLETE                         WorkersLC
+00:02:53       Nodepool1       UPDATE_COMPLETE                         demo-Nodepool1-1LYFKOKF0Y3HP
Update stack: {
  StackId: "arn:aws:cloudformation:eu-west-1:OFUSCATED"
}
Success! Your AWS resources are being updated:
Cluster Name:           demo
Controller DNS Names:   YYYYYYY.eu-west-1.elb.amazonaws.com
```

In AWS console from
```
demo-nodepool1-kube-aws-worker | i-........b3 | t2.medium | eu-west-1a | running
```
To
```
demo-nodepool1-kube-aws-worker | i-........a2 | t2.large | eu-west-1a | running
```
### Destroy

```sh
➜  cluster-test git:(s3-uri) ✗ ../bin/kube-aws destroy
This operation will destroy the cluster. Are you sure? [y,n]: y
CloudFormation stack is being destroyed. This will take several minutes
```
In Cloudformation stacks
```
demo | 2018-03-15 16:07:16 UTC+0100 | DELETE_IN_PROGRESS | kube-aws Kubernetes cluster demo
```

**Comment by jorge07** [comment]
@mumoshu Done

**Comment by mumoshu** [comment]
@jorge07 Awesome! Thank you very much for your contribution as always ☺️

**Pull request merged**
