### PR TITLE
adding in priority value in podSpec for controller, scheduler and apiserver

### PR DESCRIPTION
**Pull request by erleene**
We have found a bug in 1.13.x where mirror pods get evicted when the node is under pressure. This PR sets the priority directly so that those pods won't get evicted. We don't believe that this is required with 1.14+. 

Relates to this issue https://github.com/kubernetes/kubernetes/issues/73572

### CODE REVIEW

**Comment by davidmccormick** [comment]
Please test before we merge

**Comment by dominicgunn** [comment]
This looks to have been fixed for Kubernetes 1.13.5+, the default for kube-aws is now 1.13.7 so this shouldn't impact newly created clusters. 

Kubernetes upstream has fixed this for versions as far back as v1.11.x, do we want to do the same in kube-aws?

**Comment by davidmccormick** [comment]
Yes, that has got us confused somewhat as we observed the behavior on a 1.13.7 cluster without this work-around!  It shouldn’t happen.

**Comment by erleene** [comment]
@dominicgunn 

The problem still occurs in 1.13.7, where no controllers are running and getting evicted. We have the api server and the scheduler up, and kubelet shows the following:

```
 Jun 20 11:01:46 ip-10-16-154-255.us-west-2.compute.internal sh[1525]: E0620 11:01:46.328766    1525 certificate_manager.go:378] Certificate request was not signed: timed out waiting for the condition
Jun 20 11:01:46 ip-10-16-154-255.us-west-2.compute.internal sh[1525]: E0620 11:01:46.328804    1525 certificate_manager.go:269] Reached backoff limit, still unable to rotate certs: timed out waiting for the condition
Jun 20 11:10:49 ip-10-16-154-255.us-west-2.compute.internal sh[1525]: I0620 11:10:49.829455    1525 log.go:172] http: multiple response.WriteHeader calls
Jun 20 11:14:54 ip-10-16-154-255.us-west-2.compute.internal sh[1525]: E0620 11:14:54.907091    1525 certificate_manager.go:378] Certificate request was not signed: timed out waiting for the condition 
``` 
  some more interesting output:
``` 
Jun 20 10:49:05 ip-10-16-154-255.us-west-2.compute.internal sh[1525]: E0620 10:49:05.306713    1525 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://127.0.0.1/api/v1/services?li>
Jun 20 10:49:05 ip-10-16-154-255.us-west-2.compute.internal sh[1525]: E0620 10:49:05.307641    1525 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://127.0.0.1/api/v1/pods?fi>
Jun 20 10:49:05 ip-10-16-154-255.us-west-2.compute.internal sh[1525]: E0620 10:49:05.308780    1525 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Get https://127.0.0.1/api/v1/nodes?fieldSel>
Jun 20 10:49:05 ip-10-16-154-255.us-west-2.compute.internal sh[1525]: E0620 10:49:05.369899    1525 kubelet.go:2266] node "ip-10-16-154-255.us-west-2.compute.internal" not found
```

**Comment by dominicgunn** [comment]
Does this only happen in clusters created with kube-aws, or is it a problem in upstream k8s?

**Comment by davidmccormick** [comment]
Thanks, it was also confirmed that the controller-manager pods had been evicted - this is an upstream kubernetes issue which may also affect other releases, e.g. 1.14.x, 1.15.x (although it is supposed to have been patched).  I suggest we merge this as a work-around on 1.13.x and test the behaviour on 1.14.x and apply similar work-around if observed on that branch.

Good work Erleen!

**Comment by dominicgunn** [comment]
Cool, i'm behind that. Code looks good.

**Comment by davidmccormick** [comment]
Thanks for your first contribution! 🙏

**Pull request merged**
